//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS__User__Mangement__API.EmailComposer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfProfileInfo", Namespace="http://tempuri.org/", ItemName="profileInfo")]
    [System.SerializableAttribute()]
    public class ArrayOfProfileInfo : System.Collections.Generic.List<BTS__User__Mangement__API.EmailComposer.profileInfo> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="profileInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class profileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string infoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                if ((object.ReferenceEquals(this.infoField, value) != true)) {
                    this.infoField = value;
                    this.RaisePropertyChanged("info");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfActionList", Namespace="http://tempuri.org/", ItemName="actionList")]
    [System.SerializableAttribute()]
    public class ArrayOfActionList : System.Collections.Generic.List<BTS__User__Mangement__API.EmailComposer.actionList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="actionList", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class actionList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string labelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                if ((object.ReferenceEquals(this.labelField, value) != true)) {
                    this.labelField = value;
                    this.RaisePropertyChanged("label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailComposer.emailComposerSoap")]
    public interface emailComposerSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/queueEmail", ReplyAction="*")]
        BTS__User__Mangement__API.EmailComposer.queueEmailResponse queueEmail(BTS__User__Mangement__API.EmailComposer.queueEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/queueEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<BTS__User__Mangement__API.EmailComposer.queueEmailResponse> queueEmailAsync(BTS__User__Mangement__API.EmailComposer.queueEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queueEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queueEmail", Namespace="http://tempuri.org/", Order=0)]
        public BTS__User__Mangement__API.EmailComposer.queueEmailRequestBody Body;
        
        public queueEmailRequest() {
        }
        
        public queueEmailRequest(BTS__User__Mangement__API.EmailComposer.queueEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class queueEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string logoUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string emailSubject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contentHeading;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string mainText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool hasProfile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string profilePicUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public BTS__User__Mangement__API.EmailComposer.ArrayOfProfileInfo profileInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public BTS__User__Mangement__API.EmailComposer.ArrayOfActionList actionLists;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string detailHeading;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public BTS__User__Mangement__API.EmailComposer.ArrayOfString detailList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string recepientEmail;
        
        public queueEmailRequestBody() {
        }
        
        public queueEmailRequestBody(string username, string password, string logoUrl, string emailSubject, string contentHeading, string mainText, bool hasProfile, string profilePicUrl, BTS__User__Mangement__API.EmailComposer.ArrayOfProfileInfo profileInfo, BTS__User__Mangement__API.EmailComposer.ArrayOfActionList actionLists, string detailHeading, BTS__User__Mangement__API.EmailComposer.ArrayOfString detailList, string recepientEmail) {
            this.username = username;
            this.password = password;
            this.logoUrl = logoUrl;
            this.emailSubject = emailSubject;
            this.contentHeading = contentHeading;
            this.mainText = mainText;
            this.hasProfile = hasProfile;
            this.profilePicUrl = profilePicUrl;
            this.profileInfo = profileInfo;
            this.actionLists = actionLists;
            this.detailHeading = detailHeading;
            this.detailList = detailList;
            this.recepientEmail = recepientEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queueEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queueEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public BTS__User__Mangement__API.EmailComposer.queueEmailResponseBody Body;
        
        public queueEmailResponse() {
        }
        
        public queueEmailResponse(BTS__User__Mangement__API.EmailComposer.queueEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class queueEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string queueEmailResult;
        
        public queueEmailResponseBody() {
        }
        
        public queueEmailResponseBody(string queueEmailResult) {
            this.queueEmailResult = queueEmailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface emailComposerSoapChannel : BTS__User__Mangement__API.EmailComposer.emailComposerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class emailComposerSoapClient : System.ServiceModel.ClientBase<BTS__User__Mangement__API.EmailComposer.emailComposerSoap>, BTS__User__Mangement__API.EmailComposer.emailComposerSoap {
        
        public emailComposerSoapClient() {
        }
        
        public emailComposerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public emailComposerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public emailComposerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public emailComposerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTS__User__Mangement__API.EmailComposer.queueEmailResponse BTS__User__Mangement__API.EmailComposer.emailComposerSoap.queueEmail(BTS__User__Mangement__API.EmailComposer.queueEmailRequest request) {
            return base.Channel.queueEmail(request);
        }
        
        public string queueEmail(string username, string password, string logoUrl, string emailSubject, string contentHeading, string mainText, bool hasProfile, string profilePicUrl, BTS__User__Mangement__API.EmailComposer.ArrayOfProfileInfo profileInfo, BTS__User__Mangement__API.EmailComposer.ArrayOfActionList actionLists, string detailHeading, BTS__User__Mangement__API.EmailComposer.ArrayOfString detailList, string recepientEmail) {
            BTS__User__Mangement__API.EmailComposer.queueEmailRequest inValue = new BTS__User__Mangement__API.EmailComposer.queueEmailRequest();
            inValue.Body = new BTS__User__Mangement__API.EmailComposer.queueEmailRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.logoUrl = logoUrl;
            inValue.Body.emailSubject = emailSubject;
            inValue.Body.contentHeading = contentHeading;
            inValue.Body.mainText = mainText;
            inValue.Body.hasProfile = hasProfile;
            inValue.Body.profilePicUrl = profilePicUrl;
            inValue.Body.profileInfo = profileInfo;
            inValue.Body.actionLists = actionLists;
            inValue.Body.detailHeading = detailHeading;
            inValue.Body.detailList = detailList;
            inValue.Body.recepientEmail = recepientEmail;
            BTS__User__Mangement__API.EmailComposer.queueEmailResponse retVal = ((BTS__User__Mangement__API.EmailComposer.emailComposerSoap)(this)).queueEmail(inValue);
            return retVal.Body.queueEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTS__User__Mangement__API.EmailComposer.queueEmailResponse> BTS__User__Mangement__API.EmailComposer.emailComposerSoap.queueEmailAsync(BTS__User__Mangement__API.EmailComposer.queueEmailRequest request) {
            return base.Channel.queueEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTS__User__Mangement__API.EmailComposer.queueEmailResponse> queueEmailAsync(string username, string password, string logoUrl, string emailSubject, string contentHeading, string mainText, bool hasProfile, string profilePicUrl, BTS__User__Mangement__API.EmailComposer.ArrayOfProfileInfo profileInfo, BTS__User__Mangement__API.EmailComposer.ArrayOfActionList actionLists, string detailHeading, BTS__User__Mangement__API.EmailComposer.ArrayOfString detailList, string recepientEmail) {
            BTS__User__Mangement__API.EmailComposer.queueEmailRequest inValue = new BTS__User__Mangement__API.EmailComposer.queueEmailRequest();
            inValue.Body = new BTS__User__Mangement__API.EmailComposer.queueEmailRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.logoUrl = logoUrl;
            inValue.Body.emailSubject = emailSubject;
            inValue.Body.contentHeading = contentHeading;
            inValue.Body.mainText = mainText;
            inValue.Body.hasProfile = hasProfile;
            inValue.Body.profilePicUrl = profilePicUrl;
            inValue.Body.profileInfo = profileInfo;
            inValue.Body.actionLists = actionLists;
            inValue.Body.detailHeading = detailHeading;
            inValue.Body.detailList = detailList;
            inValue.Body.recepientEmail = recepientEmail;
            return ((BTS__User__Mangement__API.EmailComposer.emailComposerSoap)(this)).queueEmailAsync(inValue);
        }
    }
}
